### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ravencrowe01** [ravencrowe01/DrunkSquad#1]
### **Technical**
- [x] Data pull on admin login
Graphical
- [ ] Required API key level on login
- [ ] Display registration/login errors
- [ ] Pull user combat/working stats on login

### **The Great Refactor**
- [ ] Move all interfaces into DrunkSquad.Framework
- [ ] Rename base namespace to FactionSite
	- Excluding DrunkSquad
- [ ] Move as much logic as possible out of DrunkSquad
- [ ] File level namespaces
- [ ] Remove DrunkSquad from non-Startup projects
- [ ] Accessors -> Registries
- [ ] DrunkSquad.DataFetching -> FactionSite.Seeding
- [ ] Normalize DateTime usage, perhaps with a class
- [ ] Ensure all primary constructor args are being assigned to field
